spring.application.name=demo
spring.datasource.url=jdbc:postgresql://ep-ancient-truth-alfs9vnl.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_EN7WnUwTZy4C


